name: CICD
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
  actions: write
env:
  APP_NAME: "AllOPS"
  AWS_ACCESS_KEY_NAME: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_ACCESS_SECRET_NAME: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependence
        run: npm install
      - name: Run tests
        run: npm test
      # - name: Build app
      #   run: npm run build
      # - name: Deploy to production
      #   if: github.ref == 'refs/heads/main' && success()
      #   run: npm run deploy
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run: echo "Deploying to production..."
  Deploy-check:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy check1
        # run: echo "Printing app name $APP_NAME"
        run: echo "$AWS_ACCESS_KEY_NAME and $AWS_ACCESS_SECRET_NAME"
  Deploy-check2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy-check2
        run: echo "Deploy Deploy-check2"
