name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello from Allops Organization
