name: CI
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  # workflow_dispatch:
  #   inputs:
  #     logLevel:
  #       description: "Log level"
  #       required: true
  #       default: "warning"
  #       type: choice
  #       options:
  #         - info
  #         - warning
  #         - debug
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello from Allops Organization
